// Code generated by "stringer -type=Token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[_literalBeg-3]
	_ = x[IDENT-4]
	_ = x[BOOL-5]
	_ = x[INT-6]
	_ = x[FLOAT-7]
	_ = x[IMAG-8]
	_ = x[STRING-9]
	_ = x[DSTRING-10]
	_ = x[TSTRING-11]
	_ = x[EXPR-12]
	_ = x[_literalEnd-13]
	_ = x[_operatorBeg-14]
	_ = x[SUB-15]
	_ = x[LSS-16]
	_ = x[GTR-17]
	_ = x[LPAREN-18]
	_ = x[LBRACK-19]
	_ = x[LBRACE-20]
	_ = x[COMMA-21]
	_ = x[PERIOD-22]
	_ = x[RPAREN-23]
	_ = x[RBRACK-24]
	_ = x[RBRACE-25]
	_ = x[SEMICOLON-26]
	_ = x[COLON-27]
	_ = x[_operatorEnd-28]
	_ = x[_keywordBeg-29]
	_ = x[PROJECT-30]
	_ = x[TABLE-31]
	_ = x[ENUM-32]
	_ = x[REF-33]
	_ = x[AS-34]
	_ = x[TABLEGROUP-35]
	_ = x[_keywordEnd-36]
	_ = x[_miscBeg-37]
	_ = x[PRIMARY-38]
	_ = x[KEY-39]
	_ = x[PK-40]
	_ = x[NOTE-41]
	_ = x[UNIQUE-42]
	_ = x[NOT-43]
	_ = x[NULL-44]
	_ = x[INCREMENT-45]
	_ = x[DEFAULT-46]
	_ = x[INDEXES-47]
	_ = x[TYPE-48]
	_ = x[DELETE-49]
	_ = x[UPDATE-50]
	_ = x[NO-51]
	_ = x[ACTION-52]
	_ = x[RESTRICT-53]
	_ = x[SET-54]
	_ = x[_miscEnd-55]
}

const _Token_name = "ILLEGALEOFCOMMENT_literalBegIDENTBOOLINTFLOATIMAGSTRINGDSTRINGTSTRINGEXPR_literalEnd_operatorBegSUBLSSGTRLPARENLBRACKLBRACECOMMAPERIODRPARENRBRACKRBRACESEMICOLONCOLON_operatorEnd_keywordBegPROJECTTABLEENUMREFASTABLEGROUP_keywordEnd_miscBegPRIMARYKEYPKNOTEUNIQUENOTNULLINCREMENTDEFAULTINDEXESTYPEDELETEUPDATENOACTIONRESTRICTSET_miscEnd"

var _Token_index = [...]uint16{0, 7, 10, 17, 28, 33, 37, 40, 45, 49, 55, 62, 69, 73, 84, 96, 99, 102, 105, 111, 117, 123, 128, 134, 140, 146, 152, 161, 166, 178, 189, 196, 201, 205, 208, 210, 220, 231, 239, 246, 249, 251, 255, 261, 264, 268, 277, 284, 291, 295, 301, 307, 309, 315, 323, 326, 334}

func (i Token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Token_index)-1 {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[idx]:_Token_index[idx+1]]
}
